"""
Baseline report HTML renderer (Step 13.2).

Renders BaselineReportData to HTML for in-app preview and download.
Primary artifact is HTML; PDF can be added later (e.g. WeasyPrint).
"""
from __future__ import annotations

import html
from datetime import date, datetime

from backend.services.baseline_report_spec import (
    BaselineReportData,
    BaselineSummary,
    RecommendationItem,
    TopRiskItem,
)


def _escape(s: str | None) -> str:
    """Escape for HTML text content."""
    if s is None:
        return ""
    return html.escape(str(s), quote=True)


def _format_datetime(dt: datetime) -> str:
    """Format datetime for display (ISO date/time)."""
    return dt.strftime("%Y-%m-%d %H:%M UTC") if dt else ""


def _format_date(d: date) -> str:
    """Format date for display."""
    return d.strftime("%Y-%m-%d") if d else ""


def _render_summary(s: BaselineSummary) -> str:
    """Render executive summary section."""
    return f"""
<section class="baseline-summary">
  <h2>1. Executive summary</h2>
  <p><strong>Total findings:</strong> {s.total_finding_count}</p>
  <p><strong>By severity:</strong> Critical {s.critical_count}, High {s.high_count}, Medium {s.medium_count}, Low {s.low_count}, Informational {s.informational_count}</p>
  <p><strong>Open:</strong> {s.open_count} &nbsp; <strong>Resolved:</strong> {s.resolved_count}</p>
  {f'<p><strong>Scope:</strong> {s.account_count} account(s), {s.region_count} region(s)</p>' if s.account_count is not None and s.region_count is not None else ''}
  <p>{_escape(s.narrative)}</p>
  <p><em>Report date: {_format_date(s.report_date)}. Generated: {_format_datetime(s.generated_at)}</em></p>
</section>
"""


def _render_top_risks(items: list[TopRiskItem]) -> str:
    """Render top risks table."""
    rows = "".join(
        f"""
    <tr>
      <td>{_escape(item.title)}</td>
      <td>{_escape(item.resource_id)}</td>
      <td>{_escape(item.control_id)}</td>
      <td>{_escape(item.severity)}</td>
      <td>{_escape(item.account_id)}</td>
      <td>{_escape(item.region)}</td>
      <td>{_escape(item.status)}</td>
      <td>{_escape(item.recommendation_text)}</td>
    </tr>"""
        for item in items
    )
    return f"""
<section class="baseline-top-risks">
  <h2>2. Top risks</h2>
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Resource</th>
        <th>Control</th>
        <th>Severity</th>
        <th>Account</th>
        <th>Region</th>
        <th>Status</th>
        <th>Recommendation</th>
      </tr>
    </thead>
    <tbody>
{rows}
    </tbody>
  </table>
</section>
"""


def _render_recommendations(items: list[RecommendationItem]) -> str:
    """Render recommendations list."""
    bullets = "".join(f"  <li>{_escape(r.text)}</li>\n" for r in items)
    return f"""
<section class="baseline-recommendations">
  <h2>3. Recommendations</h2>
  <ul>
{bullets}
  </ul>
</section>
"""


def render_baseline_report_html(data: BaselineReportData) -> str:
    """
    Render BaselineReportData to HTML (Step 13.2).

    Produces a self-contained HTML document with summary, top risks table,
    and recommendations list. Safe for download and in-app preview.

    Args:
        data: BaselineReportData from build_baseline_report_data.

    Returns:
        HTML string (UTF-8).
    """
    title = "Baseline Security Report"
    if data.tenant_name:
        title = f"{_escape(data.tenant_name)} — Baseline Security Report"

    head = f"""
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{_escape(title)}</title>
  <style>
    body {{ font-family: system-ui, sans-serif; max-width: 900px; margin: 2rem auto; padding: 0 1rem; color: #1a1a1a; }}
    h1 {{ font-size: 1.5rem; border-bottom: 1px solid #ccc; padding-bottom: 0.5rem; }}
    h2 {{ font-size: 1.2rem; margin-top: 1.5rem; }}
    table {{ border-collapse: collapse; width: 100%; font-size: 0.9rem; }}
    th, td {{ border: 1px solid #ddd; padding: 0.4rem 0.6rem; text-align: left; }}
    th {{ background: #f5f5f5; }}
    ul {{ padding-left: 1.5rem; }}
    section {{ margin-bottom: 2rem; }}
    .meta {{ color: #666; font-size: 0.9rem; margin-bottom: 2rem; }}
  </style>
</head>
<body>
  <header>
    <h1>{_escape(title)}</h1>
    <p class="meta">Report date: {_format_date(data.summary.report_date)}. Generated: {_format_datetime(data.summary.generated_at)}.</p>
  </header>
"""

    summary_html = _render_summary(data.summary)
    top_risks_html = _render_top_risks(data.top_risks) if data.top_risks else "<section><h2>2. Top risks</h2><p>No findings in scope.</p></section>"
    rec_html = _render_recommendations(data.recommendations) if data.recommendations else "<section><h2>3. Recommendations</h2><p>No recommendations.</p></section>"

    tail = """
  <footer style="margin-top: 2rem; font-size: 0.85rem; color: #666;">
    <p>Generated by AWS Security Autopilot. This report reflects a point-in-time baseline. Full list and ongoing monitoring available in the app.</p>
  </footer>
</body>
</html>
"""
    return head + summary_html + top_risks_html + rec_html + tail
