import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Privacy Policy | Ocypheris Autopilot',
    description: 'Privacy Policy for Ocypheris Autopilot — how we collect, use, and protect your data.',
};

function Section({ number, title, children }: { number: number; title: string; children: React.ReactNode }) {
    return (
        <section style={{ marginBottom: '2.5rem' }}>
            <h2 style={{ fontSize: '1.2rem', fontWeight: 700, color: '#1f2937', marginBottom: '0.75rem', paddingBottom: '0.4rem', borderBottom: '2px solid #e5e7eb' }}>
                {number}. {title}
            </h2>
            <div style={{ color: '#374151', lineHeight: '1.8', fontSize: '0.97rem' }}>{children}</div>
        </section>
    );
}

function Sub({ title, children }: { title: string; children: React.ReactNode }) {
    return (
        <div style={{ marginTop: '1rem', marginBottom: '0.5rem' }}>
            <h3 style={{ fontSize: '1rem', fontWeight: 600, color: '#374151', marginBottom: '0.4rem' }}>{title}</h3>
            <div>{children}</div>
        </div>
    );
}

function P({ children, style }: { children: React.ReactNode; style?: React.CSSProperties }) {
    return <p style={{ marginBottom: '0.75rem', ...style }}>{children}</p>;
}

function Ul({ items }: { items: string[] }) {
    return (
        <ul style={{ listStyleType: 'disc', paddingLeft: '1.5rem', marginBottom: '0.75rem' }}>
            {items.map((item, i) => (
                <li key={i} style={{ marginBottom: '0.3rem' }}>{item}</li>
            ))}
        </ul>
    );
}

export default function PrivacyPolicyPage() {
    return (
        <div style={{ maxWidth: '820px', margin: '0 auto', padding: '3.5rem 1.5rem 5rem' }}>
            {/* Header */}
            <div style={{ marginBottom: '2.5rem' }}>
                <p style={{ fontSize: '0.78rem', fontWeight: 600, color: '#4f46e5', textTransform: 'uppercase', letterSpacing: '0.1em', marginBottom: '0.5rem' }}>Legal</p>
                <h1 style={{ fontSize: '2.25rem', fontWeight: 800, color: '#111827', marginBottom: '0.5rem', lineHeight: 1.2 }}>Privacy Policy</h1>
                <p style={{ fontSize: '0.88rem', color: '#6b7280' }}>Effective Date: December 13, 2025 &nbsp;·&nbsp; Ocypheris</p>
                <div style={{ height: '3px', width: '48px', background: '#4f46e5', borderRadius: '2px', marginTop: '1rem' }} />
            </div>

            <Section number={1} title="Introduction">
                <P>Ocypheris (&ldquo;Ocypheris,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;) is a software-as-a-service company offering the <strong>Autopilot</strong> platform — an automated AWS security operations platform that ingests findings from AWS Security Hub, Amazon GuardDuty, and IAM Access Analyzer, converts them into prioritised remediation actions, and allows authorised users to execute approved fixes directly against connected AWS environments.</P>
                <P>This Privacy Policy describes how we collect, use, store, share, and protect personal and technical data when you access or use our platform at <strong>ocypheris.com</strong> and any related APIs or services (collectively, the &ldquo;Services&rdquo;). By using the Services you agree to the practices described here. If you do not agree, do not access or use the Services.</P>
            </Section>

            <Section number={2} title="Data We Collect">
                <Sub title="2.1  Account &amp; Identity Data">
                    <P>When you register for Autopilot, we collect:</P>
                    <Ul items={['Full name, work email address, and password hash (never stored in plain text)', 'Company or organisation name', 'IP address and approximate geographic location at time of registration and login', 'User role and invite metadata (for team management)']} />
                </Sub>
                <Sub title="2.2  AWS Account Integration Data">
                    <P>To connect your AWS environment to Autopilot, you create and provide an IAM role that Ocypheris assumes via AWS Security Token Service (STS). We collect and store:</P>
                    <Ul items={['Your AWS Account ID(s)', 'IAM Role ARNs for the Read Role and Write Role', 'The ExternalId value associated with each role (used as a per-tenant security token)', 'AWS region(s) you enable for scanning', 'Connection status, last-ingest timestamps, and control-plane readiness metadata']} />
                    <P>We do <strong>not</strong> store long-lived AWS access keys or secret access keys. All access to your AWS environment uses short-lived STS-issued credentials, rotated automatically per session.</P>
                </Sub>
                <Sub title="2.3  Security Findings &amp; Actions Data">
                    <P>When Autopilot ingests your AWS environment, we receive and store data generated by AWS security services within your account:</P>
                    <Ul items={['Security Hub findings (all supported controls and standards)', 'GuardDuty threat-detection findings', 'IAM Access Analyzer findings', 'Normalised action records derived from findings (deduplication, priority scores, grouping)', 'Exception records, including the approving user, reason, and expiry date']} />
                    <P>This data is derived from your AWS environment and constitutes your organisation&apos;s security posture information. It is treated as confidential business data.</P>
                </Sub>
                <Sub title="2.4  Remediation Run Data">
                    <P>When you approve and execute a remediation action, we log:</P>
                    <Ul items={['The action type, target AWS resource, region, and account', 'The approving user and timestamp', 'Execution mode (direct fix or IaC patch bundle)', 'Pre-check and post-check results', 'Full execution log and outcome status', 'Artefact URLs for generated IaC patch bundles (stored in Amazon S3 within our AWS account)']} />
                </Sub>
                <Sub title="2.5  Evidence &amp; Compliance Export Data">
                    <P>When you generate a compliance or evidence pack, we create and store export artefacts including finding snapshots, exception attestations, control mappings, and auditor summaries. These are written to Amazon S3 in our AWS account and a download link is made available to you.</P>
                </Sub>
                <Sub title="2.6  Usage &amp; Platform Telemetry">
                    <P>We collect operational data about your use of the platform, including:</P>
                    <Ul items={['Pages visited, features used, and actions taken within the Autopilot dashboard', 'API request logs, error rates, and response latencies', 'Browser type, operating system, and device category', 'Session identifiers (stored in browser memory/localStorage; not set as persistent third-party cookies)']} />
                </Sub>
                <Sub title="2.7  Communication &amp; Support Data">
                    <Ul items={['Emails you send to us, including support requests', 'Digest email delivery logs (weekly security digest, sent to addresses you configure)', 'Slack webhook configuration (if you enable Slack digest notifications)']} />
                </Sub>
                <Sub title="2.8  Billing &amp; Payment Data">
                    <P>We process subscription payments via bank transfer. We collect and store invoice records, payment status, and the billing contact you designate. We do <strong>not</strong> store banking credentials or payment account numbers.</P>
                </Sub>
            </Section>

            <Section number={3} title="How We Use Your Data">
                <P>We use the data we collect to:</P>
                <Ul items={[
                    'Deliver the Services — authenticate users, connect to your AWS environment, ingest findings, run action engine jobs, execute approved remediations, and generate evidence packs',
                    'Operate and improve the platform — monitor performance, diagnose errors, develop new features, and train internal models on aggregate and anonymised metrics (never on your raw findings without consent)',
                    'Communicate with you — send weekly security digests, Slack notifications, product updates, billing notices, and security alerts to email addresses you configure',
                    'Fulfil legal and compliance obligations — maintain audit trails, respond to lawful requests, and comply with applicable laws',
                    'Protect security and prevent misuse — detect and respond to fraudulent or abusive use of the platform',
                ]} />
                <P>Autopilot uses <strong>automated processing</strong> to score, prioritise, and surface remediation recommendations. These automated scores are advisory tools to support human decision-making. No remediation action is executed without explicit human approval within the platform.</P>
            </Section>

            <Section number={4} title="Legal Bases for Processing (GDPR)">
                <P>For users in the European Economic Area (EEA) and United Kingdom, we process personal data under the following legal bases:</P>
                <Ul items={[
                    'Contract performance — processing necessary to deliver the Services you subscribed to',
                    'Legitimate interests — platform security, fraud prevention, and product analytics, provided these are not overridden by your rights',
                    'Legal obligation — where required by applicable law',
                    'Consent — for optional communications such as marketing emails, where we will request separate consent',
                ]} />
            </Section>

            <Section number={5} title="Data Sharing">
                <P>We do <strong>not</strong> sell your personal data. We share data only in the following circumstances:</P>
                <Sub title="5.1  AWS Services (on your behalf)">
                    <P>When Autopilot accesses your AWS environment, it interacts with AWS APIs (Security Hub, GuardDuty, IAM, STS, S3, etc.) using credentials derived from the role you grant. This access occurs within your AWS account under your account policies.</P>
                </Sub>
                <Sub title="5.2  Infrastructure &amp; Hosting Providers">
                    <P>Our platform is hosted on Amazon Web Services in the <strong>eu-north-1 (Stockholm)</strong> region. AWS acts as a sub-processor for data stored on our platform. All data is encrypted at rest and in transit.</P>
                </Sub>
                <Sub title="5.3  Email Delivery">
                    <P>We use a transactional email provider to deliver system notifications and weekly digest emails. The provider receives email addresses and message content where necessary to deliver messages on our behalf.</P>
                </Sub>
                <Sub title="5.4  Legal &amp; Regulatory Requirements">
                    <P>We may disclose your data to law enforcement, regulators, or other third parties if required by Egyptian law, EU law (where applicable), or other applicable legal authority, or to protect the legal rights and safety of Ocypheris, its users, or the public.</P>
                </Sub>
                <Sub title="5.5  Business Transfers">
                    <P>If Ocypheris undergoes a merger, acquisition, or sale of assets, your data may be transferred as part of that transaction. We will notify you before your data is subject to a different privacy policy.</P>
                </Sub>
            </Section>

            <Section number={6} title="Data Retention">
                <Ul items={[
                    'Account data: retained for the duration of your subscription and for 90 days after account closure',
                    'Security findings & actions: retained for the duration of your subscription; deleted within 60 days of account closure unless you request an earlier deletion',
                    'Remediation run logs & evidence packs: retained for the duration of your subscription plus 12 months (to support post-audit review); deleted on your written request after account closure',
                    'Billing records: retained for 7 years as required by applicable financial record-keeping obligations',
                    'Backups: encrypted database snapshots are retained for up to 30 days and automatically purged',
                ]} />
                <P>You may request deletion of your data at any time by contacting <a href="mailto:legal@ocypheris.com" style={{ color: '#4f46e5' }}>legal@ocypheris.com</a>. We will fulfil deletion requests within 30 days except where retention is required by law.</P>
            </Section>

            <Section number={7} title="Data Security">
                <P>We implement security controls appropriate to the sensitivity of the data we process, including:</P>
                <Ul items={[
                    'TLS 1.2+ encryption for all data in transit between your browser, our API, and AWS services',
                    'AES-256 encryption for all data at rest (RDS Postgres, S3)',
                    'Short-lived STS credentials for all AWS access — no long-lived AWS keys are stored',
                    'Strict tenant isolation: row-level access controls ensure each organisation can only access its own data',
                    'Least-privilege IAM policies for Autopilot\u2019s own AWS service access',
                    'CloudWatch monitoring, alerting, and audit logging for all platform activity',
                    'AWS Secrets Manager for storage of all platform secrets and credentials',
                ]} />
                <P>No security system is perfect. In the event of a data breach that affects your personal data, we will notify you and the relevant supervisory authority within 72 hours of discovery, where required by law.</P>
            </Section>

            <Section number={8} title="International Data Transfers">
                <P>Ocypheris is incorporated in Egypt. Your data is processed and stored on AWS infrastructure in the <strong>eu-north-1 (Stockholm, Sweden)</strong> region, within the European Union. If your use of the platform involves a transfer of personal data from the EEA or UK to a country not deemed adequate by the European Commission or the UK Government (including Egypt), we rely on Standard Contractual Clauses (SCCs) and the UK International Data Transfer Addendum as our legal transfer mechanisms. You may request a copy of these by contacting <a href="mailto:legal@ocypheris.com" style={{ color: '#4f46e5' }}>legal@ocypheris.com</a>.</P>
            </Section>

            <Section number={9} title="Your Rights">
                <Sub title="9.1  All Users">
                    <Ul items={[
                        'Access: Request a copy of the personal data we hold about you',
                        'Correction: Request correction of inaccurate or incomplete data',
                        'Deletion: Request deletion of your personal data, subject to legal retention obligations',
                        'Data portability: Receive your data in a structured, machine-readable format (JSON/CSV)',
                    ]} />
                </Sub>
                <Sub title="9.2  EEA &amp; UK Users (GDPR / UK GDPR)">
                    <Ul items={[
                        'Restriction of processing: Request that we limit how we process your data in certain circumstances',
                        'Object to processing: Object to processing based on legitimate interests',
                        'Withdraw consent: Where processing is based on consent, withdraw it at any time without affecting prior processing',
                        'Lodge a complaint: With your national data protection authority (DPA)',
                    ]} />
                </Sub>
                <Sub title="9.3  California Users (CCPA / CPRA)">
                    <Ul items={[
                        'Right to know what personal information is collected, used, shared, or sold',
                        'Right to delete your personal information',
                        'Right to opt-out of the sale of personal information (we do not sell your data)',
                        'Right to non-discrimination for exercising your rights',
                    ]} />
                </Sub>
                <P>To exercise any of these rights, contact us at <a href="mailto:legal@ocypheris.com" style={{ color: '#4f46e5' }}>legal@ocypheris.com</a>. We will respond within 30 days.</P>
            </Section>

            <Section number={10} title="Cookies &amp; Tracking">
                <P>Autopilot uses minimal browser storage to operate:</P>
                <Ul items={[
                    'Authentication token: A JWT token stored in browser localStorage to keep you signed in. This is a functional necessity and not a tracking cookie.',
                    'Session preferences: Theme and UI preference settings stored in localStorage.',
                ]} />
                <P>We do <strong>not</strong> use third-party advertising cookies or sell browsing data. If we introduce analytics cookies in the future, we will update this policy and seek consent where required by law. You can clear localStorage at any time through your browser settings; this will sign you out of the platform.</P>
            </Section>

            <Section number={11} title="Children's Privacy">
                <P>The Services are intended for business users aged 18 and over. We do not knowingly collect personal information from individuals under 18. If you believe we have inadvertently collected such data, please contact <a href="mailto:legal@ocypheris.com" style={{ color: '#4f46e5' }}>legal@ocypheris.com</a> and we will delete it promptly.</P>
            </Section>

            <Section number={12} title="Changes to This Policy">
                <P>We may update this Privacy Policy from time to time to reflect changes in the Services, applicable law, or our data practices. We will notify you of material changes by email to your registered address and by posting a prominent notice on <strong>ocypheris.com</strong> at least 14 days before the change takes effect. Your continued use of the Services after the effective date constitutes acceptance of the updated policy. If you do not agree to the updated policy, you must discontinue use and contact us to close your account.</P>
            </Section>

            <Section number={13} title="Contact Us">
                <P>If you have any questions, concerns, or requests regarding this Privacy Policy or your personal data, please contact:</P>
                <div style={{ background: '#f9fafb', border: '1px solid #e5e7eb', borderRadius: '8px', padding: '1.25rem 1.5rem', marginTop: '0.75rem', lineHeight: '2' }}>
                    <strong>Ocypheris — Data Privacy Team</strong><br />
                    Email: <a href="mailto:legal@ocypheris.com" style={{ color: '#4f46e5' }}>legal@ocypheris.com</a><br />
                    Website: <a href="https://ocypheris.com" style={{ color: '#4f46e5' }} target="_blank" rel="noopener noreferrer">ocypheris.com</a>
                </div>
                <P style={{ marginTop: '1rem' }}>For EEA users, if you believe your rights have not been respected, you also have the right to file a complaint with the data protection authority in your country of residence.</P>
            </Section>
        </div>
    );
}
