'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { AppShell } from '@/components/layout';
import { Button } from '@/components/ui/Button';
import { Badge } from '@/components/ui/Badge';
import { TenantIdForm } from '@/components/TenantIdForm';
import { Pagination } from '@/app/findings/Pagination';
import { useAuth } from '@/contexts/AuthContext';
import { useTenantId } from '@/lib/tenant';
import { RemediationRunListItem, getErrorMessage, listRemediationRuns } from '@/lib/api';

const PAGE_LIMIT = 50;

function statusVariant(status: string): 'success' | 'warning' | 'danger' | 'info' | 'default' {
  if (status === 'success') return 'success';
  if (status === 'pending') return 'warning';
  if (status === 'running' || status === 'awaiting_approval') return 'info';
  if (status === 'failed' || status === 'cancelled') return 'danger';
  return 'default';
}

export default function PrBundlesHistoryPage() {
  const { isAuthenticated, isLoading: authLoading, user } = useAuth();
  const { tenantId, setTenantId } = useTenantId();
  const effectiveTenantId = isAuthenticated ? undefined : tenantId;
  const showContent = isAuthenticated || Boolean(tenantId);

  const [runs, setRuns] = useState<RemediationRunListItem[]>([]);
  const [total, setTotal] = useState(0);
  const [offset, setOffset] = useState(0);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [controlId, setControlId] = useState('');
  const [resourceId, setResourceId] = useState('');
  const [appliedControlId, setAppliedControlId] = useState('');
  const [appliedResourceId, setAppliedResourceId] = useState('');

  const fetchRuns = useCallback(async () => {
    if (!showContent) {
      setIsLoading(false);
      return;
    }
    setIsLoading(true);
    setError(null);
    try {
      const page = await listRemediationRuns(
        {
          mode: 'pr_only',
          control_id: appliedControlId || undefined,
          resource_id: appliedResourceId || undefined,
          approved_by_user_id: user?.id || undefined,
          limit: PAGE_LIMIT,
          offset,
        },
        effectiveTenantId
      );
      setRuns(page.items);
      setTotal(page.total);
    } catch (err) {
      setError(getErrorMessage(err));
    } finally {
      setIsLoading(false);
    }
  }, [showContent, effectiveTenantId, user?.id, appliedControlId, appliedResourceId, offset]);

  useEffect(() => {
    fetchRuns();
  }, [fetchRuns]);

  const stats = useMemo(() => {
    const success = runs.filter((run) => run.status === 'success').length;
    const failed = runs.filter((run) => run.status === 'failed').length;
    const active = runs.filter((run) => run.status === 'pending' || run.status === 'running' || run.status === 'awaiting_approval').length;
    return { total, success, failed, active };
  }, [runs, total]);

  if (!showContent) {
    return (
      <AppShell title="PR Bundles">
        {!authLoading && isAuthenticated && <TenantIdForm onSave={setTenantId} />}
      </AppShell>
    );
  }

  return (
    <AppShell title="PR Bundles" wide>
      <div className="space-y-4">
        <div className="flex items-center justify-between rounded-[2rem] nm-neu-lg border-none p-6 sm:p-8">
          <div>
            <p className="text-sm text-muted">History of PR bundles generated by your user.</p>
            <p className="text-xs text-muted mt-1">Runs are filtered to `mode=pr_only` and `approved_by_user_id={user?.id || 'unknown'}`.</p>
          </div>
          <Link href="/pr-bundles/create">
            <Button variant="primary">Create PR Bundle</Button>
          </Link>
        </div>

        <div className="rounded-2xl nm-neu-pressed border-none p-2 overflow-x-auto no-scrollbar max-w-full">
          <div className="flex flex-wrap items-center gap-3">
            <input
              type="text"
              value={controlId}
              onChange={(event) => setControlId(event.target.value)}
              placeholder="Control ID (e.g., S3.1)"
              className="h-10 min-w-48 rounded-xl nm-neu-pressed border-none bg-transparent px-3 text-sm text-text placeholder:text-muted/60 focus:outline-none focus:ring-2 focus:ring-accent transition-all"
              aria-label="Filter bundles by control ID"
            />
            <input
              type="text"
              value={resourceId}
              onChange={(event) => setResourceId(event.target.value)}
              placeholder="Resource ID"
              className="h-10 min-w-48 rounded-xl nm-neu-pressed border-none bg-transparent px-3 text-sm text-text placeholder:text-muted/60 focus:outline-none focus:ring-2 focus:ring-accent transition-all"
              aria-label="Filter bundles by resource ID"
            />
            <Button
              variant="secondary"
              onClick={() => {
                setAppliedControlId(controlId.trim());
                setAppliedResourceId(resourceId.trim());
                setOffset(0);
              }}
              disabled={isLoading}
            >
              Apply Filters
            </Button>
            <Button
              variant="ghost"
              onClick={() => {
                setControlId('');
                setResourceId('');
                setAppliedControlId('');
                setAppliedResourceId('');
                setOffset(0);
              }}
              disabled={isLoading || (!controlId && !resourceId)}
            >
              Clear
            </Button>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-4 gap-5">
          <div className="rounded-2xl nm-neu-sm border-none p-6">
            <p className="text-xs text-muted uppercase">Total</p>
            <p className="text-2xl font-semibold text-text">{stats.total}</p>
          </div>
          <div className="rounded-2xl nm-neu-sm border-none p-6">
            <p className="text-xs text-muted uppercase">Success</p>
            <p className="text-2xl font-semibold text-text">{stats.success}</p>
            <p className="text-xs text-muted mt-1">This page</p>
          </div>
          <div className="rounded-2xl nm-neu-sm border-none p-6">
            <p className="text-xs text-muted uppercase">Failed</p>
            <p className="text-2xl font-semibold text-text">{stats.failed}</p>
            <p className="text-xs text-muted mt-1">This page</p>
          </div>
          <div className="rounded-2xl nm-neu-sm border-none p-6">
            <p className="text-xs text-muted uppercase">Active</p>
            <p className="text-2xl font-semibold text-text">{stats.active}</p>
            <p className="text-xs text-muted mt-1">This page</p>
          </div>
        </div>

        {error && (
          <div className="rounded-2xl nm-neu-flat border border-danger/30 bg-danger/10 p-4 text-sm text-danger">
            {error}
          </div>
        )}

        <div className="rounded-[2rem] nm-neu-lg border-none overflow-hidden p-2">
          <table className="w-full text-sm">
            <thead className="bg-bg">
              <tr className="text-left text-muted">
                <th className="px-4 py-3">Run</th>
                <th className="px-4 py-3">Status</th>
                <th className="px-4 py-3">Created</th>
                <th className="px-4 py-3">Completed</th>
                <th className="px-4 py-3">Summary</th>
                <th className="px-4 py-3">Action</th>
              </tr>
            </thead>
            <tbody>
              {isLoading && (
                <tr>
                  <td className="px-4 py-6 text-muted" colSpan={6}>
                    Loading PR bundle history...
                  </td>
                </tr>
              )}
              {!isLoading && runs.length === 0 && (
                <tr>
                  <td className="px-4 py-6 text-muted" colSpan={6}>
                    No PR bundles generated yet.
                  </td>
                </tr>
              )}
              {!isLoading &&
                runs.map((run) => (
                  <tr key={run.id} className="border-t border-border/60">
                    <td className="px-4 py-3 font-mono text-muted">{run.id}</td>
                    <td className="px-4 py-3">
                      <Badge variant={statusVariant(run.status)}>{run.status}</Badge>
                    </td>
                    <td className="px-4 py-3 text-muted">{new Date(run.created_at).toLocaleString()}</td>
                    <td className="px-4 py-3 text-muted">{run.completed_at ? new Date(run.completed_at).toLocaleString() : '—'}</td>
                    <td className="px-4 py-3 text-text">{run.artifacts_summary || 'PR bundle'}</td>
                    <td className="px-4 py-3">
                      <Link href={`/remediation-runs/${run.id}`} className="text-accent hover:underline">
                        Open
                      </Link>
                    </td>
                  </tr>
                ))}
            </tbody>
          </table>
        </div>
        <Pagination
          offset={offset}
          limit={PAGE_LIMIT}
          total={total}
          onPageChange={setOffset}
          itemLabel="runs"
        />
      </div>
    </AppShell>
  );
}
